name: Deploy Flask App with Terraform

on:
  push:
    branches: [ main ]
    
permissions:
  contents: read
  actions: write
  id-token: write
env:
  AWS_REGION: ca-central-1
  ECR_REPOSITORY: greeting-app
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${AWS_REGION} |sudo docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${AWS_REGION}.amazonaws.com  

      - name: Terraform Apply with DB creds
        env:
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        run: |
          cd terraform
          terraform init -reconfigure
          #terraform destroy -auto-approve
          terraform apply -auto-approve
          terraform output -json > terraform_outputs.json

      - name: Build, Tag, and Push Docker image
        run: |
            IMAGE_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}"
            aws ecr get-login-password --region ca-central-1 | sudo docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${AWS_REGION}.amazonaws.com     
            
            sudo docker build -t python-app .
            docker tag python-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${AWS_REGION}.amazonaws.com/greeting-app:latest

            aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${AWS_REGION}.amazonaws.com
            docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${AWS_REGION}.amazonaws.com/greeting-app:latest


      - name: Upload Terraform Outputs
        uses: actions/upload-artifact@v4
        with:
          name: deploy # The name of the artifact
          path: terraform/terraform_outputs.json

          
